### ISSUE TITLE
"This question type does not support the given operation"

### ISSUE THREAD

**Issue by dureyingenieria** [Humanitas-Labs/export-google-form#1]
Every time I try to run the script, I get this error message:
`Sorry, this question type does not support the given operation. (line 69, file "Code")`

I am testing with a very simple form document, a single short answer question.

Thanks for your time.

**Comment by dureyingenieria** [comment]
I've solved it adding these lines (I don't have permissions to make a Pull Request):

Line 69:
```java
    // Skip feedback-related keys
    if ("getFeedbackForIncorrect".equals(getKey) || "getFeedbackForCorrect".equals(getKey)
      || "getGeneralFeedback".equals(getKey)) {return};
```

**Comment by stevenschmatz** [comment]
Thank you so much for the proposed change! Nice catch. I added that line, thanks again 👍
